# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Comments
comments:
  gitment: 
    clientId: 92f184604996b38bf3db
    clientSecret: bef7ed99058ae78c149689d4521f5c55fda6afed

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-139142924-1
gauges_analytics:
favicon: /favicon.png
twitter:
fb_admins:
fb_app_id:
